### ISSUE TITLE
JS Modules

### ISSUE THREAD

**Issue by iammasoodalam** [itsshahbazhere/tictactoe#1]
# use modules while using vite.
You should use js modules like this:
```html
<script src="./script.js" type="module"></script>
<script src="./functions.js type="module"></script>
```
this will allow you to maintain your code better and vite will also keep that modular in the final build.
and if you don't provide the `type="module"` then your js file will not be added in the final build.

**Comment by itsshahbazhere** [comment]
Thanks for your help.
